//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Valve.VR
{
    using System;
    using UnityEngine;
    
    
    public class SteamVR_Input_ActionSet_GeologieVirtuelle : Valve.VR.SteamVR_ActionSet
    {
        
        public virtual SteamVR_Action_Boolean ActivateGeneralInterface
        {
            get
            {
                return SteamVR_Actions.geologieVirtuelle_ActivateGeneralInterface;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActivateMeasureInterface
        {
            get
            {
                return SteamVR_Actions.geologieVirtuelle_ActivateMeasureInterface;
            }
        }
        
        public virtual SteamVR_Action_Boolean ActivateMeasurePointer
        {
            get
            {
                return SteamVR_Actions.geologieVirtuelle_ActivateMeasurePointer;
            }
        }
        
        public virtual SteamVR_Action_Boolean PlacePoint
        {
            get
            {
                return SteamVR_Actions.geologieVirtuelle_PlacePoint;
            }
        }
        
        public virtual SteamVR_Action_Boolean PlacePlane
        {
            get
            {
                return SteamVR_Actions.geologieVirtuelle_PlacePlane;
            }
        }
        
        public virtual SteamVR_Action_Boolean PlaceMarker
        {
            get
            {
                return SteamVR_Actions.geologieVirtuelle_PlaceMarker;
            }
        }
        
        public virtual SteamVR_Action_Boolean PlaceWulfElement
        {
            get
            {
                return SteamVR_Actions.geologieVirtuelle_PlaceWulfElement;
            }
        }
        
        public virtual SteamVR_Action_Boolean MoveElement
        {
            get
            {
                return SteamVR_Actions.geologieVirtuelle_MoveElement;
            }
        }
        
        public virtual SteamVR_Action_Boolean DisplayResults
        {
            get
            {
                return SteamVR_Actions.geologieVirtuelle_DisplayResults;
            }
        }
    }
}
